spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: rien
    url: jdbc:mysql://localhost:3306/JPA
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false